### ISSUE TITLE
GitHub actions badges

### ISSUE THREAD

**Issue by mgedmin** [ProgrammersOfVilnius/zope3.pov.lt#1]
ZopeFoundation is moving to GitHub actions.  For projects that have a .github/workflows/tests.yml instead of a .travis.yml I need to generate new badges.

Example for zope.browser:
- image URL: https://github.com/zopefoundation/zope.browser/workflows/tests/badge.svg
- link target: https://github.com/zopefoundation/zope.browser/actions?query=workflow%3A%22tests%22

**Comment by mgedmin** [comment]
The badges are generated in Javascript:
https://github.com/ProgrammersOfVilnius/zope3.pov.lt/blob/9213ab659bcc75c1ef56c116855822e423a80be2/py3/index.html#L258-L263
https://github.com/ProgrammersOfVilnius/zope3.pov.lt/blob/9213ab659bcc75c1ef56c116855822e423a80be2/py3/travis.html#L154-L159

**Comment by mgedmin** [comment]
How can I determine whether a particular package uses GHA or Travis?

https://github.com/mgedmin/ztk-py3-status/blob/master/get_deps.py looks inside sdists.  I'm not sure the GitHub workflows are included in sdists.  I could look for badge URLs in long_description, but I don't want to wait for a PyPI release to get the right badge.  

I don't see any has_actions/has_workflows in https://developer.github.com/v3/repos/#list-organization-repositories.

Maybe I need to ghcloneall all the ZF repos somewhere?

**Comment by sallner** [comment]
Using a the GitHub package https://pypi.org/project/PyGithub/ and the GitHub-API with access tokens it is possible to check for specific files in a repo without downloading everything. I used something similar to detect pre-commit configurations. We could check for `.meta.toml` in the case of zopefoundation.

```python
from github import Github
from github import UnknownObjectException

def check_precommit_yml(repo):
    """Check, whether a .pre-commit-config.yml is missing in the repo."""
    try:
        repo.get_contents('.pre-commit-config.yaml')
    except UnknownObjectException:
        return True
    return False

gh = Github('access-token')
gocept = gh.get_organization('zopefoundation')
active_public_repos = [
    repo
    for repo in gocept.get_repos()
    if not repo.archived
]
no_precommit_repos = [
    repo for repo in active_public_repos if check_precommit_yml(repo)]

```

I know, that this introduces a new dependency on to this script _and_ also requires a token to run. But on the other hand I do not see proxy for GHA other than add a badge for GHA actions and see, whether it goes green. 

Alternatively we could check the contents of `setup.cfg`? As the should be a section containing the string `.meta.toml`
```
[check-manifest]
ignore = 
	.editorconfig
	.meta.toml
```

Whatever is chosen, I would really support a new column with this information.

**Comment by mgedmin** [comment]
The repos are public, we could do a simple HTTP GET for https://github.com/zopefoundation/PACKAGE/tree/master/.github/workflows and see if the response code is 200 or 404.

**Comment by mgedmin** [comment]
Or I could just generate badges for everything and see what happens

**Comment by sallner** [comment]
It might be better to ask for forgiveness than for permission in this case.

**Comment by mgedmin** [comment]
Ok, let's see what happens: https://zope3.pov.lt/py3/gha.html

![Ekrano nuotrauka iš 2021-03-03 11-03-57](https://user-images.githubusercontent.com/159967/109780984-2f4f9e00-7c10-11eb-89e1-ff18ca82b49c.png)

Broken images everywhere!

**Comment by jugmac00** [comment]
I missed the fix! Thank you so much!
